### ISSUE TITLE
Multiple processes sharing the same in-memory cache

### ISSUE THREAD

**Issue by ddorian** [Yiling-J/theine#22]
AFAIK nothing exists in Python. Maybe you can configure a shared address space or something and multiple processes be able to share the same cache.

**Comment by Yiling-J** [comment]
There are some use case of shared memory: [UltraDict](https://github.com/ronny-rentner/UltraDict) and [Shared Memory Dict](https://github.com/luizalabs/shared-memory-dict). But I think all of them have to serialize object to bytes before sending data to manager, this would add some overheads, and may cause problems. That's could be the reason why shared memory cache is not popular in Python. 
So instead of hacking something, I think waiting for Python's no-gil multithreading might be a better choice.

**Comment by ddorian** [comment]
I'll probably use diskcache or a sqlite alternative in the meantime. Feel free to close the issue. Thank you.
