### ISSUE TITLE
How can i set the timeout callback

### ISSUE THREAD

**Issue by STofone** [Yiling-J/theine#26]
As title, i want to call method of the item when it is removed because of timeout.

**Comment by Yiling-J** [comment]
@STofone
It's not possible to set timeout callback in Theine(Python) currently. I'm not actively developing new features at the moment as I'm not using Python or Rust recently. The need to split the package into two languages due to Python's limitations also has been a bit frustrating to me. Tha't why my Go version of Theine is significantly more feature-rich. However, contributions are always welcome!
